version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: crset_postgres
    environment:
      POSTGRES_DB: crset_db
      POSTGRES_USER: crset_user
      POSTGRES_PASSWORD: crset_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crset_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crset_user -d crset_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: crset_backend
    environment:
      - DATABASE_URL=postgresql://crset_user:crset_password@postgres:5432/crset_db
      - SECRET_KEY=crset-solutions-secret-key-2025-very-secure-and-long
      - RESEND_API_KEY=${RESEND_API_KEY:-re_demo_key}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_demo}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - crset_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build: ./frontend
    container_name: crset_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_demo}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - crset_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  crset_network:
    driver: bridge

